name: Bug Report
description: Something isn't working as expected
labels: [bug]
body:
  - type: input
    id: version
    attributes:
      label: SpireScope version
      placeholder: 'e.g. v2.6.0'
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: OS
      options: [Windows, macOS, Linux, Steam Deck]
    validations:
      required: true
  - type: input
    id: python-version
    attributes:
      label: Python version
      placeholder: 'e.g. 3.11.4 (skip if using .exe)'
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
    validations:
      required: true
  - type: textarea
    id: repro-steps
    attributes:
      label: Steps to reproduce
    validations:
      required: true
